[tool.black]
line-length = 100
target-version = ["py312"]

[tool.isort]
profile = "black"
src_paths = ["orso"]
extend_skip_glob = ["tests/**", "*.pyx"]
line_length = 100
multi_line_output = 9
force_single_line = true
float_to_top = true

[tool.ruff]
line-length = 100
indent-width = 4
target-version = 'py312'

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 100

[tool.ruff.lint]
select = ["SIM", "NPY201"]
ignore = []