name: planet_data_pipeline
description: Pipeline to filter and save user data
tenant: acme_corp
classification: confidential
access_model: row-level
trigger:
  schedule: "0 4 * * *"
  timezone: "UTC"

schema:
  - name: name
    description: Full name of the planet
    type: varchar
    expectations:
      not_null: true
      min_length: 2

steps:
  - name: load_data
    uses: internal/sql@1.0.0
    config:
      statement: |
        SELECT
          name
        FROM
          $planets

  - name: filter_data
    uses: internal/filter@latest
    config:
      conditions:
        - [["name", "!=", 'Mars']]

  - name: save_results
    uses: internal/save@1.0.0
    config:
      endpoint: "https://{{ environment.HOST }}/upload"
      username: "{{ secrets.API_USER }}"
      password: "{{ secrets.API_PASSWORD }}"
