name: user_data_pipeline
description: Pipeline to filter and save user data
tenant: acme_corp
classification: confidential
access_model: row-level
trigger:
  schedule: "0 4 * * *"
  timezone: "UTC"

schema:
  - name: name
    description: Full name of the user
    type: varchar
    expectations:
      not_null: true
      min_length: 2

  - name: age
    description: Age of the user
    type: integer
    expectations:
      min: 0

steps:
  - name: load_data
    uses: internal/read_gcs
    config:
      path: "data.csv"

  - name: filter_data
    uses: internal/filter
    config:
      min_length: 4

  - name: save_results
    uses: internal/save
    config:
      endpoint: "https://{{ environment.HOST }}/upload"
      username: "{{ secrets.API_USER }}"
      password: "{{ secrets.API_PASSWORD }}"

  - name: aggregate_sales
    uses: internal/sql
    config:
      sql: |
        SELECT
          region,
          SUM(sales_amount) AS total_sales
        FROM
          input_table
        GROUP BY
          region

  - name: validate_age
    uses: internal/python
    config:
      code: |
        import orjson
        def run(data, context):
            if data.get("age", 0) < 18:
                context["flagged"] = True
            return data, context